[env:xiao_mg24]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-mg24-sense
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem39BB80F43
monitor_port = /dev/cu.usbmodem39BB80F43

build_src_filter =
    +<main.cpp>

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    arduino-libraries/SD@^1.3.0
    olikraus/U8g2@^2.35.9
    https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_XIAO_MG24
    -DU8X8_DO_NOT_SET_WIRE_CLOCK

[env:sim800_smoke_test]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-mg24
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem39BB80F43
monitor_port = /dev/cu.usbmodem39BB80F43

build_src_filter =
    +<sim800_smoke_test.cpp>
